application:
  port: 8080
  hmac_secret: "super-long-adn-secret-random-key-needed-to-verify-message-integrity"
database:
  host: 192.168.3.5
  port: 5432
  username: postgres
  password: 123456
  database_name: newsletter
email_client:
  timeout_milliseconds: 10000
redis_uri: redis://localhost:6379